// World capitals dataset — name, country, ISO-2, lat, lng, region
// 196 capitals. Coordinates are city centers.
window.CAPITALS = [
  // Africa
  { name: "Algiers",          country: "Algeria",                iso: "DZ", lat: 36.7538, lng: 3.0588,    region: "Africa" },
  { name: "Luanda",           country: "Angola",                 iso: "AO", lat: -8.8390, lng: 13.2894,   region: "Africa" },
  { name: "Porto-Novo",       country: "Benin",                  iso: "BJ", lat: 6.4969,  lng: 2.6283,    region: "Africa" },
  { name: "Gaborone",         country: "Botswana",               iso: "BW", lat: -24.6282,lng: 25.9231,   region: "Africa" },
  { name: "Ouagadougou",      country: "Burkina Faso",           iso: "BF", lat: 12.3714, lng: -1.5197,   region: "Africa" },
  { name: "Bujumbura",        country: "Burundi",                iso: "BI", lat: -3.3614, lng: 29.3599,   region: "Africa" },
  { name: "Yaoundé",          country: "Cameroon",               iso: "CM", lat: 3.8480,  lng: 11.5021,   region: "Africa" },
  { name: "Praia",            country: "Cape Verde",             iso: "CV", lat: 14.9330, lng: -23.5133,  region: "Africa" },
  { name: "Bangui",           country: "Central African Republic", iso: "CF", lat: 4.3947, lng: 18.5582, region: "Africa" },
  { name: "N'Djamena",        country: "Chad",                   iso: "TD", lat: 12.1348, lng: 15.0557,   region: "Africa" },
  { name: "Moroni",           country: "Comoros",                iso: "KM", lat: -11.7172,lng: 43.2473,   region: "Africa" },
  { name: "Kinshasa",         country: "DR Congo",               iso: "CD", lat: -4.4419, lng: 15.2663,   region: "Africa" },
  { name: "Brazzaville",      country: "Congo",                  iso: "CG", lat: -4.2634, lng: 15.2429,   region: "Africa" },
  { name: "Djibouti",         country: "Djibouti",               iso: "DJ", lat: 11.8251, lng: 42.5903,   region: "Africa" },
  { name: "Cairo",            country: "Egypt",                  iso: "EG", lat: 30.0444, lng: 31.2357,   region: "Africa" },
  { name: "Malabo",           country: "Equatorial Guinea",      iso: "GQ", lat: 3.7523,  lng: 8.7742,    region: "Africa" },
  { name: "Asmara",           country: "Eritrea",                iso: "ER", lat: 15.3229, lng: 38.9251,   region: "Africa" },
  { name: "Mbabane",          country: "Eswatini",               iso: "SZ", lat: -26.3054,lng: 31.1367,   region: "Africa" },
  { name: "Addis Ababa",      country: "Ethiopia",               iso: "ET", lat: 9.0320,  lng: 38.7469,   region: "Africa" },
  { name: "Libreville",       country: "Gabon",                  iso: "GA", lat: 0.4162,  lng: 9.4673,    region: "Africa" },
  { name: "Banjul",           country: "Gambia",                 iso: "GM", lat: 13.4549, lng: -16.5790,  region: "Africa" },
  { name: "Accra",            country: "Ghana",                  iso: "GH", lat: 5.6037,  lng: -0.1870,   region: "Africa" },
  { name: "Conakry",          country: "Guinea",                 iso: "GN", lat: 9.5370,  lng: -13.6785,  region: "Africa" },
  { name: "Bissau",           country: "Guinea-Bissau",          iso: "GW", lat: 11.8636, lng: -15.5977,  region: "Africa" },
  { name: "Yamoussoukro",     country: "Côte d'Ivoire",          iso: "CI", lat: 6.8276,  lng: -5.2893,   region: "Africa" },
  { name: "Nairobi",          country: "Kenya",                  iso: "KE", lat: -1.2921, lng: 36.8219,   region: "Africa" },
  { name: "Maseru",           country: "Lesotho",                iso: "LS", lat: -29.3151,lng: 27.4869,   region: "Africa" },
  { name: "Monrovia",         country: "Liberia",                iso: "LR", lat: 6.3008,  lng: -10.7972,  region: "Africa" },
  { name: "Tripoli",          country: "Libya",                  iso: "LY", lat: 32.8872, lng: 13.1913,   region: "Africa" },
  { name: "Antananarivo",     country: "Madagascar",             iso: "MG", lat: -18.8792,lng: 47.5079,   region: "Africa" },
  { name: "Lilongwe",         country: "Malawi",                 iso: "MW", lat: -13.9626,lng: 33.7741,   region: "Africa" },
  { name: "Bamako",           country: "Mali",                   iso: "ML", lat: 12.6392, lng: -8.0029,   region: "Africa" },
  { name: "Nouakchott",       country: "Mauritania",             iso: "MR", lat: 18.0735, lng: -15.9582,  region: "Africa" },
  { name: "Port Louis",       country: "Mauritius",              iso: "MU", lat: -20.1609,lng: 57.5012,   region: "Africa" },
  { name: "Rabat",            country: "Morocco",                iso: "MA", lat: 34.0209, lng: -6.8417,   region: "Africa" },
  { name: "Maputo",           country: "Mozambique",             iso: "MZ", lat: -25.9692,lng: 32.5732,   region: "Africa" },
  { name: "Windhoek",         country: "Namibia",                iso: "NA", lat: -22.5594,lng: 17.0832,   region: "Africa" },
  { name: "Niamey",           country: "Niger",                  iso: "NE", lat: 13.5117, lng: 2.1251,    region: "Africa" },
  { name: "Abuja",            country: "Nigeria",                iso: "NG", lat: 9.0765,  lng: 7.3986,    region: "Africa" },
  { name: "Kigali",           country: "Rwanda",                 iso: "RW", lat: -1.9706, lng: 30.1044,   region: "Africa" },
  { name: "São Tomé",         country: "São Tomé and Príncipe",  iso: "ST", lat: 0.3365,  lng: 6.7273,    region: "Africa" },
  { name: "Dakar",            country: "Senegal",                iso: "SN", lat: 14.7167, lng: -17.4677,  region: "Africa" },
  { name: "Victoria",         country: "Seychelles",             iso: "SC", lat: -4.6191, lng: 55.4513,   region: "Africa" },
  { name: "Freetown",         country: "Sierra Leone",           iso: "SL", lat: 8.4657,  lng: -13.2317,  region: "Africa" },
  { name: "Mogadishu",        country: "Somalia",                iso: "SO", lat: 2.0469,  lng: 45.3182,   region: "Africa" },
  { name: "Pretoria",         country: "South Africa",           iso: "ZA", lat: -25.7479,lng: 28.2293,   region: "Africa" },
  { name: "Juba",             country: "South Sudan",            iso: "SS", lat: 4.8594,  lng: 31.5713,   region: "Africa" },
  { name: "Khartoum",         country: "Sudan",                  iso: "SD", lat: 15.5007, lng: 32.5599,   region: "Africa" },
  { name: "Dodoma",           country: "Tanzania",               iso: "TZ", lat: -6.1630, lng: 35.7516,   region: "Africa" },
  { name: "Lomé",             country: "Togo",                   iso: "TG", lat: 6.1725,  lng: 1.2314,    region: "Africa" },
  { name: "Tunis",            country: "Tunisia",                iso: "TN", lat: 36.8065, lng: 10.1815,   region: "Africa" },
  { name: "Kampala",          country: "Uganda",                 iso: "UG", lat: 0.3476,  lng: 32.5825,   region: "Africa" },
  { name: "Lusaka",           country: "Zambia",                 iso: "ZM", lat: -15.3875,lng: 28.3228,   region: "Africa" },
  { name: "Harare",           country: "Zimbabwe",               iso: "ZW", lat: -17.8252,lng: 31.0335,   region: "Africa" },

  // Asia
  { name: "Kabul",            country: "Afghanistan",            iso: "AF", lat: 34.5553, lng: 69.2075,   region: "Asia" },
  { name: "Yerevan",          country: "Armenia",                iso: "AM", lat: 40.1792, lng: 44.4991,   region: "Asia" },
  { name: "Baku",             country: "Azerbaijan",             iso: "AZ", lat: 40.4093, lng: 49.8671,   region: "Asia" },
  { name: "Manama",           country: "Bahrain",                iso: "BH", lat: 26.2285, lng: 50.5860,   region: "Asia" },
  { name: "Dhaka",            country: "Bangladesh",             iso: "BD", lat: 23.8103, lng: 90.4125,   region: "Asia" },
  { name: "Thimphu",          country: "Bhutan",                 iso: "BT", lat: 27.4728, lng: 89.6390,   region: "Asia" },
  { name: "Bandar Seri Begawan", country: "Brunei",              iso: "BN", lat: 4.9031,  lng: 114.9398,  region: "Asia" },
  { name: "Phnom Penh",       country: "Cambodia",               iso: "KH", lat: 11.5564, lng: 104.9282,  region: "Asia" },
  { name: "Beijing",          country: "China",                  iso: "CN", lat: 39.9042, lng: 116.4074,  region: "Asia" },
  { name: "Nicosia",          country: "Cyprus",                 iso: "CY", lat: 35.1856, lng: 33.3823,   region: "Asia" },
  { name: "Tbilisi",          country: "Georgia",                iso: "GE", lat: 41.7151, lng: 44.8271,   region: "Asia" },
  { name: "New Delhi",        country: "India",                  iso: "IN", lat: 28.6139, lng: 77.2090,   region: "Asia" },
  { name: "Jakarta",          country: "Indonesia",              iso: "ID", lat: -6.2088, lng: 106.8456,  region: "Asia" },
  { name: "Tehran",           country: "Iran",                   iso: "IR", lat: 35.6892, lng: 51.3890,   region: "Asia" },
  { name: "Baghdad",          country: "Iraq",                   iso: "IQ", lat: 33.3152, lng: 44.3661,   region: "Asia" },
  { name: "Jerusalem",        country: "Israel",                 iso: "IL", lat: 31.7683, lng: 35.2137,   region: "Asia" },
  { name: "Tokyo",            country: "Japan",                  iso: "JP", lat: 35.6762, lng: 139.6503,  region: "Asia" },
  { name: "Amman",            country: "Jordan",                 iso: "JO", lat: 31.9454, lng: 35.9284,   region: "Asia" },
  { name: "Astana",           country: "Kazakhstan",             iso: "KZ", lat: 51.1605, lng: 71.4704,   region: "Asia" },
  { name: "Kuwait City",      country: "Kuwait",                 iso: "KW", lat: 29.3759, lng: 47.9774,   region: "Asia" },
  { name: "Bishkek",          country: "Kyrgyzstan",             iso: "KG", lat: 42.8746, lng: 74.5698,   region: "Asia" },
  { name: "Vientiane",        country: "Laos",                   iso: "LA", lat: 17.9757, lng: 102.6331,  region: "Asia" },
  { name: "Beirut",           country: "Lebanon",                iso: "LB", lat: 33.8938, lng: 35.5018,   region: "Asia" },
  { name: "Kuala Lumpur",     country: "Malaysia",               iso: "MY", lat: 3.1390,  lng: 101.6869,  region: "Asia" },
  { name: "Malé",             country: "Maldives",               iso: "MV", lat: 4.1755,  lng: 73.5093,   region: "Asia" },
  { name: "Ulaanbaatar",      country: "Mongolia",               iso: "MN", lat: 47.8864, lng: 106.9057,  region: "Asia" },
  { name: "Naypyidaw",        country: "Myanmar",                iso: "MM", lat: 19.7633, lng: 96.0785,   region: "Asia" },
  { name: "Kathmandu",        country: "Nepal",                  iso: "NP", lat: 27.7172, lng: 85.3240,   region: "Asia" },
  { name: "Pyongyang",        country: "North Korea",            iso: "KP", lat: 39.0392, lng: 125.7625,  region: "Asia" },
  { name: "Muscat",           country: "Oman",                   iso: "OM", lat: 23.5859, lng: 58.4059,   region: "Asia" },
  { name: "Islamabad",        country: "Pakistan",               iso: "PK", lat: 33.6844, lng: 73.0479,   region: "Asia" },
  { name: "Ramallah",         country: "Palestine",              iso: "PS", lat: 31.9038, lng: 35.2034,   region: "Asia" },
  { name: "Manila",           country: "Philippines",            iso: "PH", lat: 14.5995, lng: 120.9842,  region: "Asia" },
  { name: "Doha",             country: "Qatar",                  iso: "QA", lat: 25.2854, lng: 51.5310,   region: "Asia" },
  { name: "Riyadh",           country: "Saudi Arabia",           iso: "SA", lat: 24.7136, lng: 46.6753,   region: "Asia" },
  { name: "Singapore",        country: "Singapore",              iso: "SG", lat: 1.3521,  lng: 103.8198,  region: "Asia" },
  { name: "Seoul",            country: "South Korea",            iso: "KR", lat: 37.5665, lng: 126.9780,  region: "Asia" },
  { name: "Colombo",          country: "Sri Lanka",              iso: "LK", lat: 6.9271,  lng: 79.8612,   region: "Asia" },
  { name: "Damascus",         country: "Syria",                  iso: "SY", lat: 33.5138, lng: 36.2765,   region: "Asia" },
  { name: "Dushanbe",         country: "Tajikistan",             iso: "TJ", lat: 38.5598, lng: 68.7870,   region: "Asia" },
  { name: "Bangkok",          country: "Thailand",               iso: "TH", lat: 13.7563, lng: 100.5018,  region: "Asia" },
  { name: "Dili",             country: "Timor-Leste",            iso: "TL", lat: -8.5569, lng: 125.5603,  region: "Asia" },
  { name: "Ankara",           country: "Turkey",                 iso: "TR", lat: 39.9334, lng: 32.8597,   region: "Asia" },
  { name: "Ashgabat",         country: "Turkmenistan",           iso: "TM", lat: 37.9601, lng: 58.3261,   region: "Asia" },
  { name: "Abu Dhabi",        country: "United Arab Emirates",   iso: "AE", lat: 24.4539, lng: 54.3773,   region: "Asia" },
  { name: "Tashkent",         country: "Uzbekistan",             iso: "UZ", lat: 41.2995, lng: 69.2401,   region: "Asia" },
  { name: "Hanoi",            country: "Vietnam",                iso: "VN", lat: 21.0285, lng: 105.8542,  region: "Asia" },
  { name: "Sana'a",           country: "Yemen",                  iso: "YE", lat: 15.3694, lng: 44.1910,   region: "Asia" },

  // Europe
  { name: "Tirana",           country: "Albania",                iso: "AL", lat: 41.3275, lng: 19.8187,   region: "Europe" },
  { name: "Andorra la Vella", country: "Andorra",                iso: "AD", lat: 42.5063, lng: 1.5218,    region: "Europe" },
  { name: "Vienna",           country: "Austria",                iso: "AT", lat: 48.2082, lng: 16.3738,   region: "Europe" },
  { name: "Minsk",            country: "Belarus",                iso: "BY", lat: 53.9006, lng: 27.5590,   region: "Europe" },
  { name: "Brussels",         country: "Belgium",                iso: "BE", lat: 50.8503, lng: 4.3517,    region: "Europe" },
  { name: "Sarajevo",         country: "Bosnia and Herzegovina", iso: "BA", lat: 43.8563, lng: 18.4131,   region: "Europe" },
  { name: "Sofia",            country: "Bulgaria",               iso: "BG", lat: 42.6977, lng: 23.3219,   region: "Europe" },
  { name: "Zagreb",           country: "Croatia",                iso: "HR", lat: 45.8150, lng: 15.9819,   region: "Europe" },
  { name: "Prague",           country: "Czech Republic",         iso: "CZ", lat: 50.0755, lng: 14.4378,   region: "Europe" },
  { name: "Copenhagen",       country: "Denmark",                iso: "DK", lat: 55.6761, lng: 12.5683,   region: "Europe" },
  { name: "Tallinn",          country: "Estonia",                iso: "EE", lat: 59.4370, lng: 24.7536,   region: "Europe" },
  { name: "Helsinki",         country: "Finland",                iso: "FI", lat: 60.1699, lng: 24.9384,   region: "Europe" },
  { name: "Paris",            country: "France",                 iso: "FR", lat: 48.8566, lng: 2.3522,    region: "Europe" },
  { name: "Berlin",           country: "Germany",                iso: "DE", lat: 52.5200, lng: 13.4050,   region: "Europe" },
  { name: "Athens",           country: "Greece",                 iso: "GR", lat: 37.9838, lng: 23.7275,   region: "Europe" },
  { name: "Budapest",         country: "Hungary",                iso: "HU", lat: 47.4979, lng: 19.0402,   region: "Europe" },
  { name: "Reykjavik",        country: "Iceland",                iso: "IS", lat: 64.1466, lng: -21.9426,  region: "Europe" },
  { name: "Dublin",           country: "Ireland",                iso: "IE", lat: 53.3498, lng: -6.2603,   region: "Europe" },
  { name: "Rome",             country: "Italy",                  iso: "IT", lat: 41.9028, lng: 12.4964,   region: "Europe" },
  { name: "Pristina",         country: "Kosovo",                 iso: "XK", lat: 42.6629, lng: 21.1655,   region: "Europe" },
  { name: "Riga",             country: "Latvia",                 iso: "LV", lat: 56.9496, lng: 24.1052,   region: "Europe" },
  { name: "Vaduz",            country: "Liechtenstein",          iso: "LI", lat: 47.1410, lng: 9.5209,    region: "Europe" },
  { name: "Vilnius",          country: "Lithuania",              iso: "LT", lat: 54.6872, lng: 25.2797,   region: "Europe" },
  { name: "Luxembourg",       country: "Luxembourg",             iso: "LU", lat: 49.6116, lng: 6.1319,    region: "Europe" },
  { name: "Valletta",         country: "Malta",                  iso: "MT", lat: 35.8997, lng: 14.5147,   region: "Europe" },
  { name: "Chișinău",         country: "Moldova",                iso: "MD", lat: 47.0105, lng: 28.8638,   region: "Europe" },
  { name: "Monaco",           country: "Monaco",                 iso: "MC", lat: 43.7384, lng: 7.4246,    region: "Europe" },
  { name: "Podgorica",        country: "Montenegro",             iso: "ME", lat: 42.4304, lng: 19.2594,   region: "Europe" },
  { name: "Amsterdam",        country: "Netherlands",            iso: "NL", lat: 52.3676, lng: 4.9041,    region: "Europe" },
  { name: "Skopje",           country: "North Macedonia",        iso: "MK", lat: 41.9981, lng: 21.4254,   region: "Europe" },
  { name: "Oslo",             country: "Norway",                 iso: "NO", lat: 59.9139, lng: 10.7522,   region: "Europe" },
  { name: "Warsaw",           country: "Poland",                 iso: "PL", lat: 52.2297, lng: 21.0122,   region: "Europe" },
  { name: "Lisbon",           country: "Portugal",               iso: "PT", lat: 38.7223, lng: -9.1393,   region: "Europe" },
  { name: "Bucharest",        country: "Romania",                iso: "RO", lat: 44.4268, lng: 26.1025,   region: "Europe" },
  { name: "Moscow",           country: "Russia",                 iso: "RU", lat: 55.7558, lng: 37.6173,   region: "Europe" },
  { name: "San Marino",       country: "San Marino",             iso: "SM", lat: 43.9424, lng: 12.4578,   region: "Europe" },
  { name: "Belgrade",         country: "Serbia",                 iso: "RS", lat: 44.7866, lng: 20.4489,   region: "Europe" },
  { name: "Bratislava",       country: "Slovakia",               iso: "SK", lat: 48.1486, lng: 17.1077,   region: "Europe" },
  { name: "Ljubljana",        country: "Slovenia",               iso: "SI", lat: 46.0569, lng: 14.5058,   region: "Europe" },
  { name: "Madrid",           country: "Spain",                  iso: "ES", lat: 40.4168, lng: -3.7038,   region: "Europe" },
  { name: "Stockholm",        country: "Sweden",                 iso: "SE", lat: 59.3293, lng: 18.0686,   region: "Europe" },
  { name: "Bern",             country: "Switzerland",            iso: "CH", lat: 46.9480, lng: 7.4474,    region: "Europe" },
  { name: "Kyiv",             country: "Ukraine",                iso: "UA", lat: 50.4501, lng: 30.5234,   region: "Europe" },
  { name: "London",           country: "United Kingdom",         iso: "GB", lat: 51.5074, lng: -0.1278,   region: "Europe" },
  { name: "Vatican City",     country: "Vatican City",           iso: "VA", lat: 41.9029, lng: 12.4534,   region: "Europe" },

  // Americas
  { name: "Buenos Aires",     country: "Argentina",              iso: "AR", lat: -34.6037,lng: -58.3816,  region: "Americas" },
  { name: "Nassau",           country: "Bahamas",                iso: "BS", lat: 25.0343, lng: -77.3963,  region: "Americas" },
  { name: "Bridgetown",       country: "Barbados",               iso: "BB", lat: 13.1939, lng: -59.5432,  region: "Americas" },
  { name: "Belmopan",         country: "Belize",                 iso: "BZ", lat: 17.2510, lng: -88.7590,  region: "Americas" },
  { name: "Sucre",            country: "Bolivia",                iso: "BO", lat: -19.0196,lng: -65.2619,  region: "Americas" },
  { name: "Brasília",         country: "Brazil",                 iso: "BR", lat: -15.7975,lng: -47.8919,  region: "Americas" },
  { name: "Ottawa",           country: "Canada",                 iso: "CA", lat: 45.4215, lng: -75.6972,  region: "Americas" },
  { name: "Santiago",         country: "Chile",                  iso: "CL", lat: -33.4489,lng: -70.6693,  region: "Americas" },
  { name: "Bogotá",           country: "Colombia",               iso: "CO", lat: 4.7110,  lng: -74.0721,  region: "Americas" },
  { name: "San José",         country: "Costa Rica",             iso: "CR", lat: 9.9281,  lng: -84.0907,  region: "Americas" },
  { name: "Havana",           country: "Cuba",                   iso: "CU", lat: 23.1136, lng: -82.3666,  region: "Americas" },
  { name: "Roseau",           country: "Dominica",               iso: "DM", lat: 15.3017, lng: -61.3879,  region: "Americas" },
  { name: "Santo Domingo",    country: "Dominican Republic",     iso: "DO", lat: 18.4861, lng: -69.9312,  region: "Americas" },
  { name: "Quito",            country: "Ecuador",                iso: "EC", lat: -0.1807, lng: -78.4678,  region: "Americas" },
  { name: "San Salvador",     country: "El Salvador",            iso: "SV", lat: 13.6929, lng: -89.2182,  region: "Americas" },
  { name: "St. George's",     country: "Grenada",                iso: "GD", lat: 12.0561, lng: -61.7488,  region: "Americas" },
  { name: "Guatemala City",   country: "Guatemala",              iso: "GT", lat: 14.6349, lng: -90.5069,  region: "Americas" },
  { name: "Georgetown",       country: "Guyana",                 iso: "GY", lat: 6.8013,  lng: -58.1551,  region: "Americas" },
  { name: "Port-au-Prince",   country: "Haiti",                  iso: "HT", lat: 18.5944, lng: -72.3074,  region: "Americas" },
  { name: "Tegucigalpa",      country: "Honduras",               iso: "HN", lat: 14.0723, lng: -87.1921,  region: "Americas" },
  { name: "Kingston",         country: "Jamaica",                iso: "JM", lat: 18.0179, lng: -76.8099,  region: "Americas" },
  { name: "Mexico City",      country: "Mexico",                 iso: "MX", lat: 19.4326, lng: -99.1332,  region: "Americas" },
  { name: "Managua",          country: "Nicaragua",              iso: "NI", lat: 12.1364, lng: -86.2514,  region: "Americas" },
  { name: "Panama City",      country: "Panama",                 iso: "PA", lat: 8.9824,  lng: -79.5199,  region: "Americas" },
  { name: "Asunción",         country: "Paraguay",               iso: "PY", lat: -25.2637,lng: -57.5759,  region: "Americas" },
  { name: "Lima",             country: "Peru",                   iso: "PE", lat: -12.0464,lng: -77.0428,  region: "Americas" },
  { name: "Basseterre",       country: "Saint Kitts and Nevis",  iso: "KN", lat: 17.3026, lng: -62.7177,  region: "Americas" },
  { name: "Castries",         country: "Saint Lucia",            iso: "LC", lat: 14.0101, lng: -60.9875,  region: "Americas" },
  { name: "Kingstown",        country: "Saint Vincent",          iso: "VC", lat: 13.1600, lng: -61.2248,  region: "Americas" },
  { name: "St. John's",       country: "Antigua and Barbuda",    iso: "AG", lat: 17.1175, lng: -61.8456,  region: "Americas" },
  { name: "Paramaribo",       country: "Suriname",               iso: "SR", lat: 5.8520,  lng: -55.2038,  region: "Americas" },
  { name: "Port of Spain",    country: "Trinidad and Tobago",    iso: "TT", lat: 10.6918, lng: -61.2225,  region: "Americas" },
  { name: "Washington D.C.",  country: "United States",          iso: "US", lat: 38.9072, lng: -77.0369,  region: "Americas" },
  { name: "Montevideo",       country: "Uruguay",                iso: "UY", lat: -34.9011,lng: -56.1645,  region: "Americas" },
  { name: "Caracas",          country: "Venezuela",              iso: "VE", lat: 10.4806, lng: -66.9036,  region: "Americas" },

  // Oceania
  { name: "Canberra",         country: "Australia",              iso: "AU", lat: -35.2809,lng: 149.1300,  region: "Oceania" },
  { name: "Suva",             country: "Fiji",                   iso: "FJ", lat: -18.1416,lng: 178.4419,  region: "Oceania" },
  { name: "Tarawa",           country: "Kiribati",               iso: "KI", lat: 1.4518,  lng: 172.9717,  region: "Oceania" },
  { name: "Majuro",           country: "Marshall Islands",       iso: "MH", lat: 7.1164,  lng: 171.1854,  region: "Oceania" },
  { name: "Palikir",          country: "Micronesia",             iso: "FM", lat: 6.9248,  lng: 158.1611,  region: "Oceania" },
  { name: "Yaren",            country: "Nauru",                  iso: "NR", lat: -0.5477, lng: 166.9209,  region: "Oceania" },
  { name: "Wellington",       country: "New Zealand",            iso: "NZ", lat: -41.2865,lng: 174.7762,  region: "Oceania" },
  { name: "Ngerulmud",        country: "Palau",                  iso: "PW", lat: 7.5004,  lng: 134.6242,  region: "Oceania" },
  { name: "Port Moresby",     country: "Papua New Guinea",       iso: "PG", lat: -9.4438, lng: 147.1803,  region: "Oceania" },
  { name: "Apia",             country: "Samoa",                  iso: "WS", lat: -13.8506,lng: -171.7513, region: "Oceania" },
  { name: "Honiara",          country: "Solomon Islands",        iso: "SB", lat: -9.4456, lng: 159.9729,  region: "Oceania" },
  { name: "Nuku'alofa",       country: "Tonga",                  iso: "TO", lat: -21.1393,lng: -175.2026, region: "Oceania" },
  { name: "Funafuti",         country: "Tuvalu",                 iso: "TV", lat: -8.5243, lng: 179.1942,  region: "Oceania" },
  { name: "Port Vila",        country: "Vanuatu",                iso: "VU", lat: -17.7334,lng: 168.3273,  region: "Oceania" }
];
