// Color themes for the map. Each theme is a complete palette.
// Users can switch presets, then fine-tune individual colors in the panel.
window.THEMES = {
  "google-light": {
    name: "Google Light",
    bg:          "#dde6ea",
    water:       "#aadaff",
    land:        "#f5f1e6",
    landStroke:  "#cfc6b0",
    border:      "#cfc6b0",
    graticule:   "#dcd3bd",
    cityFill:    "#ea4335",
    cityRing:    "#ffffff",
    cityHalo:    "#ea4335",
    label:       "#1f2937",
    labelHalo:   "#ffffff",
    line:        "#1a73e8",
    lineGlow:    "#74a9ff",
    pulse:       "#1a73e8",
    highlightFill:   "#ffe98a",
    highlightStroke: "#f29d12",
    sea:             "#0e9488"
  },
  "google-dark": {
    name: "Google Dark",
    bg:          "#0e1827",
    water:       "#17263c",
    land:        "#2c3a4f",
    landStroke:  "#3d4d65",
    border:      "#3d4d65",
    graticule:   "#243349",
    cityFill:    "#ffd166",
    cityRing:    "#1b2a40",
    cityHalo:    "#ffd166",
    label:       "#e8edf5",
    labelHalo:   "#0e1827",
    line:        "#7aa2ff",
    lineGlow:    "#5a82e0",
    pulse:       "#7aa2ff",
    highlightFill:   "#3b4d6d",
    highlightStroke: "#ffd166",
    sea:             "#2dd4bf"
  },
  "midnight": {
    name: "Midnight Cobalt",
    bg:          "#020715",
    water:       "#06101f",
    land:        "#0f1e36",
    landStroke:  "#1e3358",
    border:      "#1e3358",
    graticule:   "#13243f",
    cityFill:    "#00e0ff",
    cityRing:    "#06101f",
    cityHalo:    "#00e0ff",
    label:       "#cfe6ff",
    labelHalo:   "#06101f",
    line:        "#00e0ff",
    lineGlow:    "#3fa5ff",
    pulse:       "#00e0ff",
    highlightFill:   "#1f3a66",
    highlightStroke: "#00e0ff",
    sea:             "#ff8a3d"
  },
  "paper": {
    name: "Paper",
    bg:          "#e3dcc8",
    water:       "#efe9da",
    land:        "#fbf8ef",
    landStroke:  "#b9ad8c",
    border:      "#b9ad8c",
    graticule:   "#d9cea9",
    cityFill:    "#c0392b",
    cityRing:    "#fbf8ef",
    cityHalo:    "#c0392b",
    label:       "#403624",
    labelHalo:   "#fbf8ef",
    line:        "#7c4b1f",
    lineGlow:    "#c98a4b",
    pulse:       "#c0392b",
    highlightFill:   "#fff2c4",
    highlightStroke: "#c0392b",
    sea:             "#2a7fa8"
  },
  "mono": {
    name: "Mono",
    bg:          "#dadada",
    water:       "#ffffff",
    land:        "#eeeeee",
    landStroke:  "#9aa0a6",
    border:      "#9aa0a6",
    graticule:   "#dadada",
    cityFill:    "#111111",
    cityRing:    "#ffffff",
    cityHalo:    "#111111",
    label:       "#111111",
    labelHalo:   "#ffffff",
    line:        "#111111",
    lineGlow:    "#888888",
    pulse:       "#111111",
    highlightFill:   "#cfd8e3",
    highlightStroke: "#111111",
    sea:             "#7a8791"
  },
  "noir": {
    name: "Noir",
    bg:          "#000000",
    water:       "#0a0a0a",
    land:        "#1a1a1a",
    landStroke:  "#2a2a2a",
    border:      "#2a2a2a",
    graticule:   "#161616",
    cityFill:    "#ffffff",
    cityRing:    "#0a0a0a",
    cityHalo:    "#ffffff",
    label:       "#f2f2f2",
    labelHalo:   "#0a0a0a",
    line:        "#ffffff",
    lineGlow:    "#999999",
    pulse:       "#ffffff",
    highlightFill:   "#2a2a2a",
    highlightStroke: "#ffffff",
    sea:             "#6f7e86"
  },
  "sunset": {
    name: "Sunset",
    bg:          "#0c0617",
    water:       "#1a0e2e",
    land:        "#3d1f4a",
    landStroke:  "#5e3170",
    border:      "#5e3170",
    graticule:   "#2c1639",
    cityFill:    "#ffb86b",
    cityRing:    "#1a0e2e",
    cityHalo:    "#ff6f91",
    label:       "#ffe4c4",
    labelHalo:   "#1a0e2e",
    line:        "#ff6f91",
    lineGlow:    "#ffb86b",
    pulse:       "#ff6f91",
    highlightFill:   "#5b2c66",
    highlightStroke: "#ff6f91",
    sea:             "#3fd0c8"
  },
  "ocean": {
    name: "Ocean",
    bg:          "#04141f",
    water:       "#072a3f",
    land:        "#0d4664",
    landStroke:  "#1a6585",
    border:      "#1a6585",
    graticule:   "#0f3a55",
    cityFill:    "#7be4cc",
    cityRing:    "#072a3f",
    cityHalo:    "#7be4cc",
    label:       "#d6f1ea",
    labelHalo:   "#072a3f",
    line:        "#7be4cc",
    lineGlow:    "#2bb39a",
    pulse:       "#7be4cc",
    highlightFill:   "#0e597a",
    highlightStroke: "#7be4cc",
    sea:             "#ffb05c"
  },
  "matrix": {
    name: "Matrix",
    bg:          "#000000",
    water:       "#000000",
    land:        "#001a0e",
    landStroke:  "#00ff41",
    border:      "#00b32d",
    graticule:   "#003314",
    cityFill:    "#00ff41",
    cityRing:    "#000000",
    cityHalo:    "#00ff41",
    label:       "#a9ffb9",
    labelHalo:   "#000000",
    line:        "#00ff41",
    lineGlow:    "#a9ffb9",
    pulse:       "#00ff41",
    highlightFill:   "#003b1e",
    highlightStroke: "#00ff41",
    sea:             "#00e5ff"
  }
};

window.THEME_ORDER = [
  "google-light","google-dark","midnight","paper","mono","noir","sunset","ocean","matrix"
];
